pakStrings pakStrings[] = {
        "Start With Saved Data",
        "Spieldaten laden",
        "Charger donn)es jeu",
        //
        "Create New Game",
        "Neues Spiel starten",
        "Commencer une nouvelle partie",
        //
        "Start Game Without Saving",
        "Spiel ohne Speichern starten",
        "Commencer la partie sans sauvegarder",
        //
        "Manage Controller Pak",
        "Controller Pak organisieren",
        "Gestion cartouche de sauvegarde",
        //
        "Repair Pak",
        "Controller Pak reparieren",
        "R)parer cartouche de sauvegarde",
        //
        "EMPTY                   ",
        "LEER            ",
        "VIDE            ",
        "EMPTY                   ",
        "LEER            ",
        "VIDE            ",
        "EMPTY                   ",
        "LEER            ",
        "VIDE            ",
        "EMPTY                   ",
        "LEER            ",
        "VIDE            ",
        "EMPTY                   ",
        "LEER            ",
        "VIDE            ",
        "EMPTY                   ",
        "LEER            ",
        "VIDE            ",
        "EMPTY                   ",
        "LEER            ",
        "VIDE            ",
        "EMPTY                   ",
        "LEER            ",
        "VIDE            ",
        "EMPTY                   ",
        "LEER            ",
        "VIDE            ",
        "EMPTY                   ",
        "LEER            ",
        "VIDE            ",
        "EMPTY                   ",
        "LEER            ",
        "VIDE            ",
        "EMPTY                   ",
        "LEER            ",
        "VIDE            ",
        "EMPTY                   ",
        "LEER            ",
        "VIDE            ",
        "EMPTY                   ",
        "LEER            ",
        "VIDE            ",
        "EMPTY                   ",
        "LEER            ",
        "VIDE            ",
        "EMPTY                   ",
        "LEER            ",
        "VIDE            "
};
