#ifndef SYSTEM_PROPS_H
#define SYSTEM_PROPS_H

#define SYSTEM_PROPID_GFX_SETTINGS 1
#define SYSTEM_PROPID_MAX_SPRITES 6
#define SYSTEM_PROPID_GEOMETRY_SETTINGS 7
#define SYSTEM_PROPID_IMTX_STACK_COUNT 8
#define SYSTEM_PROPID_DOBJ_SETTINGS 10
#define SYSTEM_PROPID_CHANNEL_SETTINGS 11
#define SYSTEM_PROPID_VERTEX_COUNT 14
#define SYSTEM_PROPID_LIGHTS_SETTINGS 15
#define SYSTEM_PROPID_AUDIOMGR_SETTINGS 2
#define SYSTEM_PROP_COUNT 24


#endif /* SYSTEM_PROPS_H */
